### ISSUE TITLE
Database conection

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#26]
Hello. 

I have created file database.yml in config folder. It looks so:
```
production:
  adapter: postgresql
  encoding: utf8
  database: prudge
  username: prudge
  password: 17401725
  pool: 5

development:
  adapter: postgresql
  encoding: utf8
  hostname: localhost
  port: 5432
  database: prudge
  pool: 5
  username: prudge
  password: 17401725

test:
  adapter: postgresql
  encoding: utf8
  database: prudge_test
  username: postgres
  password:
  pool: 5
```
After executing `bundle exec rake db:schema:load --trace` I get this:
```rake aborted!
FATAL:  Peer authentication failed for user "prudge"
/var/www/prudge/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:schema:load => environment
(See full trace by running task with --trace)```

How to fix it?
