### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#27]
I will describe the full process of installation so it may be easier for you to find my fail.

I have installed rbenv and downloaded ruby 1.9.3-p448 with it.

After I have created folder /var/www/prudge and cloned repository in it.
I have installed memcached, postgresql, redis-server and sphinxsearch also.

After I made `bundle install` and all needed gems were added successfully. I created a postgresql user and database, gave needed permissions to that user.
I created database.yml in config folder:
```
production:
  adapter: postgresql
  encoding: utf8
  database: prudge_prod
  username: postgres
  password:
  pool: 5

development:
  adapter: postgresql
  encoding: utf8
  database: prudge
  host: localhost
  port: 5432
  username: aurora
  password: prudge
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: prudge_test
  username: postgres
  password:
  pool: 5
```

After that I tried to make `bundle exec rake db:schema:load` but it failed and said that I don't have some config files in config folder. So I created some of theme using the examples. Now I have these files also:
**config.yml**:
```
host: "aurora.alexfoxy.ru"
time_zone: 'Asia/Yekaterinburg'
default_locale: 'ru'
```
**languages.yml**:
```
-
  name: C
  compiler: /usr/bin/gcc -x c -lm %{source} -o %{output}
  description: GCC version 4.8.2
-
  name: Pascal
  extension: pas
  compiler: /usr/bin/fpc %{source} -o%{source}
  description: Free Pascal Compiler version 2.6.2-8
-
  name: C++
  compiler: /usr/bin/g++ -O3 -x c++ %{source} -o %{output}
  description: g++ gcc version 4.8.2
-
  name: Java
  compiler: /usr/bin/gcj %{source} -o %{output} --main=%{basename} -lm
  memory: 14000
  description: gcj gcc version 4.8.2
-
  name: Ruby
  extension: '.rb'
  interpreter: /usr/bin/ruby
  memory: 60000
  time: 2
  description: ruby 4.8.2-p448
  processes: 3
-
  name: Python
  extension: '.py'
  interpreter: /usr/bin/python3
  memory: 60000
  time: 2
  description: Python 3.2
-
  name: Go
  compiler: /usr/bin/go build -o %{output} %{source}
  description: go version go1.4.2
```
**mail.yml**:
```
# Send email using sendmail
delivery_method: :sendmail
sendmail_settings:
  location: '/usr/sbin/sendmail'
  arguments: '-i -t'

# Send with gmail
#delivery_method: :smtp
#smtp_settings:
#  address: smtp.gmail.com
#  port: 587
#  authentication: plain
#  enable_starttls_auto: true
#  user_name: example@gmail.com
#  password: secret
```
**resque.yml**:
```
development:
  redis: localhost:6379
  namespace: prudge

test:
  redis: localhost:6379
  namespace: test:prudge

production:
  redis: your.redis.server:6379
  namespace: prudge
```
**settings.yml**:
```
defaults: &defaults
  name: "Aurora"
  slogan: "Code is a poetry"
  copyright: "All rights reserved"
  description: "Programming contest organization, problem solving site"
  notifier: "aurora@alexfoxy.ru"
  judge: 'judge'

development:
  <<: *defaults

test:
  <<: *defaults
  judge: 'spec/judge'

production:
  <<: *defaults
```
**sphinx.yml**:
```
development: &my_settings
  mem_limit: 256M
  port: 3317
  listen: 127.0.0.1:3317
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  html_strip: 1
  charset_type: utf-8
  charset_table: a..z, A..Z->a..z, 0..9, U+0430..U+044f, U+0410..U+042f->U+0430$

test:
  <<: *my_settings

production:
  <<: *my_settings
  pid_file: /usr/apps/prudge/shared/pids/sphinx.pid
  config_file: /usr/apps/prudge/shared/config/sphinx.conf
  searchd_file_path: /usr/apps/prudge/shared/sphinx
  searchd_binary_name: /usr/local/sbin/searchd
  indexer_binary_name: /usr/local/bin/indexer
```
**twitter.yml**:
```
consumer_key: YOUR_CONSUMER_KEY
consumer_secret: YOUR_CONSUMER_SECRET
access_token: YOUR_ACCESS_TOKEN
access_secret: YOUR_ACCESS_SECRET
```

After I made `bundle exec rails server` and it told me that there are some permissions problems with `tmp` folder. I have created it and chmod 777. After all was ok and it said that the server is woking on host: `http://0.0.0.0:5000`

I made `git submodule update --init` and tried to `make` but it said:
```
gcc -c error.c -Wall -ansi -pedantic
Assembler messages:
Fatal error: can't create error.o: Permission denied
make: *** [all] Error 1
```
so I made `sudo make` but got:
```
gcc -c error.c -Wall -ansi -pedantic
gcc -c safe.c -Wall -ansi -pedantic
gcc -c safeexec.c -Wall -ansi -pedantic
safeexec.c:23:17: fatal error: kvm.h: No such file or directory
 #include <kvm.h>
                 ^
compilation terminated.
make: *** [all] Error 1
```

I tried to make `QUEUE=* bundle exec rake resque:work` after that all but just see an empty window and nothing happens. Please correct me and help.

I can email you my SSH credentials so you could better see it. Thanks!
