### ISSUE TITLE
Fix en.yml

### ISSUE THREAD

**Issue by alexbagirov** [ochko/prudge#35]
This problem is related to #34 
I have added a new file called `layouts.yml` that will describe top menu's strings in `mn:` language. We need to fix `en.yml` file because it links to `en:` which is not for Prudge.

**Comment by ochko** [comment]
You can define localizations for multiple languages in one yml file:

```yml
mn:
  layouts:
    application:
      ....
      ....
en:
  layouts:
    application:
      ....
      ....
ru:
  layouts:
    application:
      ....
      ....

```
